add cjis to compliance demo
ansible/product-demos pull request #134
Opened 2024-02-20 19:36 UTC by l3acon

This should be fairly simple, though I had some issues during testing. On RHEL7 I encountered jobs that failed without any error messages. I would normally chalk it up to the random gremlins but it happened more than once. Maybe @jce-redhat or someone has seen something similar?

Anyway, this at least worked once on rhel7 and rhel8.

2024-02-20 19:56 UTC, jce-redhat requested changes
added a couple of ideas for you to try, lemme know if you want help testing

2024-02-20 19:56 UTC, jce-redhat commented on linux/cjis-prerequisites.yml
> +# The CJIS role seems to assume these packages are installed and the
@l3acon i haven't tested this yet, but i took a look at the CJIS role and i believe you won't need to install and enable firewalld and NetworkManager if the following variables get set:

```
service_firewalld_enabled: false
firewalld_sshd_port_enabled: false
```

these can be added to the [LINUX / Multi-profile Compliance](https://github.com/ansible/product-demos/blob/10f0bb46414c56481a8fb0e58a4d927f2c9b2235/linux/setup.yml#L362) job template as long as the other CaC roles don't use variables of the same name.

2024-02-20 19:56 UTC, jce-redhat commented on linux/compliance-enforce.yml
> +
if you add "cjis" to the [survey spec](https://github.com/ansible/product-demos/blob/10f0bb46414c56481a8fb0e58a4d927f2c9b2235/linux/setup.yml#L384) for the "LINUX / Multi-profile compliance" job template definition, you shouldn't need to add this separate task for calling the CJIS role.

2024-03-03 19:44 UTC, jce-redhat approved these changes

2024-03-03 19:46 UTC, merged

2024-03-03 23:44 UTC, l3acon commented
Yay thanks @jce-redhat