Patch EC2 Workflow
ansible/product-demos pull request #75
Opened 2023-06-20 21:25 UTC by zjleblanc

# General

Create a patching workflow that snapshots an EC2, applies patches, and restores from a snapshot if the patch fails. 

## Playbooks
- snapshot_ec2
- patch_ec2
- restore_ec2

## Workflow
- Cloud / AWS / Patch Workflow
![Screenshot 2023-06-20 at 4 24 44 PM](https://github.com/ansible/product-demos/assets/6855624/dc8ee16f-db4c-40a4-9473-4594d83a3627)

2023-06-21 18:51 UTC, willtome commented
@zjleblanc is this a duplicate of #74 ?

2023-07-24 18:56 UTC, zjleblanc commented
@willtome yes, I went ahead and closed the other one.

2023-07-24 19:34 UTC, willtome commented
Thanks @zjleblanc. Lets try reusing the existing patch jobs in the workflow. See example starting here https://github.com/ansible/product-demos/blob/81f35e8d67bd6971ae0f75ad0f7ec222cd757daa/satellite/setup.yml#L196

2023-08-09 23:58 UTC, zjleblanc commented
@willtome updated this PR to use the existing linux patching job template. I added it to the cloud setup, not sure if there is a better way to reference the controller_config object while ensuring it's created without having to run the full linux setup.

2023-08-28 20:22 UTC, willtome requested changes

2023-08-28 20:22 UTC, willtome commented on cloud/setup.yml
> +    inventory: Workshop Inventory
Change to Demo Inventory

2023-08-28 20:22 UTC, willtome commented on cloud/setup.yml
> +    inventory: Workshop Inventory
Change to Demo Inventory

2023-08-28 20:22 UTC, willtome commented on cloud/setup.yml
> +    inventory: "Workshop Inventory"
Change to Demo Inventory

2023-08-28 20:22 UTC, willtome commented on cloud/setup.yml
> +      - "Workshop Credential"
Change to Demo Credential

2023-08-29 14:28 UTC, willtome commented
does this PR also resolve https://github.com/ansible/product-demos/issues/83? Something additional to test

2023-09-11 20:00 UTC, merged